// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SugarERP.Infrastructure.Local;

#nullable disable

namespace SugarERP.Infrastructure.Local.Migrations
{
    [DbContext(typeof(BranchDbContext))]
    [Migration("20260909221057_InitialBranchType1")]
    partial class InitialBranchType1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("SugarERP.Domain.CashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId", "OccurredAtUtc");

                    b.HasIndex("SourceId", "Kind")
                        .IsUnique();

                    b.ToTable("cash_movements", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RetailPriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("catalog_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_catalog_item_price", "\"RetailPriceMinor\" >= 0");

                            t.HasCheckConstraint("ck_catalog_item_scale", "\"QuantityScale\" > 0");

                            t.HasCheckConstraint("ck_catalog_item_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.DeviceConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceCredential")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TouchMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("device_configuration", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_configuration_singleton", "\"Id\" = 1");

                            t.HasCheckConstraint("ck_device_configuration_type1", "\"Profile\" = 'BranchType1'");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("sync_inbox", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependenciesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("DeviceSequence")
                        .IsUnique();

                    b.HasIndex("State", "NextAttemptAtUtc");

                    b.ToTable("sync_outbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_sequence", "\"DeviceSequence\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fulfillment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SubtotalMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TipMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("ShiftId");

                    b.HasIndex("BusinessDate", "OccurredAtUtc");

                    b.ToTable("sales", null, t =>
                        {
                            t.HasCheckConstraint("ck_sale_money", "\"SubtotalMinor\" >= 0 AND \"DiscountMinor\" >= 0 AND \"TipMinor\" >= 0 AND \"TotalMinor\" >= 0");

                            t.HasCheckConstraint("ck_sale_total", "\"TotalMinor\" = \"SubtotalMinor\" - \"DiscountMinor\" + \"TipMinor\"");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AllocatedDiscountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuantityScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleId", "ItemId")
                        .IsUnique();

                    b.ToTable("sale_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_sale_line_money", "\"UnitPriceMinor\" >= 0 AND \"AllocatedDiscountMinor\" >= 0 AND \"TotalMinor\" >= 0");

                            t.HasCheckConstraint("ck_sale_line_quantity", "\"QuantityScaled\" > 0 AND \"QuantityScale\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.SalePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("sale_payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_sale_payment_amount", "\"AmountMinor\" >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.SequenceState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextDeviceSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextReceiptSequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sequence_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_sequence_positive", "\"NextDeviceSequence\" > 0 AND \"NextReceiptSequence\" > 0");

                            t.HasCheckConstraint("ck_sequence_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActualCashMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpectedCashMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningCashMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Open'");

                    b.HasIndex("BusinessDate", "Kind");

                    b.ToTable("shifts", null, t =>
                        {
                            t.HasCheckConstraint("ck_shift_cash", "\"OpeningCashMinor\" >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.ShiftItemSnapshot", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActualCloseScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AdjustmentScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpectedCloseScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IncomingScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KitchenReturnScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningQuantityScaled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SoldScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long>("WasteScaled")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShiftId", "ItemId");

                    b.ToTable("shift_item_snapshots", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.StockBalance", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityScaled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("stock_balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_balance_nonnegative", "\"QuantityScaled\" >= 0");

                            t.HasCheckConstraint("ck_stock_balance_revision", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DeltaScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceLineId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "OccurredAtUtc");

                    b.HasIndex("SourceLineId", "Kind")
                        .IsUnique();

                    b.ToTable("stock_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_movement_nonzero", "\"DeltaScaled\" <> 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.Sale", b =>
                {
                    b.HasOne("SugarERP.Domain.Shift", "Shift")
                        .WithMany("Sales")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SugarERP.Domain.SaleLine", b =>
                {
                    b.HasOne("SugarERP.Domain.Sale", "Sale")
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SugarERP.Domain.SalePayment", b =>
                {
                    b.HasOne("SugarERP.Domain.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SugarERP.Domain.ShiftItemSnapshot", b =>
                {
                    b.HasOne("SugarERP.Domain.Shift", "Shift")
                        .WithMany("OpeningItems")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SugarERP.Domain.StockBalance", b =>
                {
                    b.HasOne("SugarERP.Domain.CatalogItem", "Item")
                        .WithOne("StockBalance")
                        .HasForeignKey("SugarERP.Domain.StockBalance", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SugarERP.Domain.CatalogItem", b =>
                {
                    b.Navigation("StockBalance");
                });

            modelBuilder.Entity("SugarERP.Domain.Sale", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SugarERP.Domain.Shift", b =>
                {
                    b.Navigation("OpeningItems");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
