// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SugarERP.Infrastructure.Local;

#nullable disable

namespace SugarERP.Infrastructure.Local.Migrations
{
    [DbContext(typeof(BranchDbContext))]
    [Migration("20260915125526_AddBranch2InventoryLedger")]
    partial class AddBranch2InventoryLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("SugarERP.Domain.AdjustmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AdminDecisionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppliedDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountLineId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProposedDeltaScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountLineId")
                        .IsUnique();

                    b.ToTable("adjustment_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_adjustment_request_nonzero", "\"ProposedDeltaScaled\" <> 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.BranchInventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("Kind", "ReferenceId")
                        .IsUnique();

                    b.ToTable("branch_inventory_transactions", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.BranchInventoryTransactionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DeltaScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TransactionId", "ItemId", "Location")
                        .IsUnique();

                    b.ToTable("branch_inventory_transaction_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_delta_nonzero", "DeltaScaled <> 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.BranchLocalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExportDirectory")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("branch_local_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_branch_settings_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.BranchLocationBalance", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityScaled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "Location");

                    b.ToTable("branch_location_balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_location_balance_nonnegative", "QuantityScaled >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.CafeCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("cafe_customers", null, t =>
                        {
                            t.HasCheckConstraint("ck_cafe_customer_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.CafePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CafeCustomerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("CafeCustomerId", "ItemId")
                        .IsUnique();

                    b.ToTable("cafe_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_cafe_price_nonnegative", "\"UnitPriceMinor\" >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.CashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId", "OccurredAtUtc");

                    b.HasIndex("SourceId", "Kind")
                        .IsUnique();

                    b.ToTable("cash_movements", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RetailPriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("catalog_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_catalog_item_price", "\"RetailPriceMinor\" >= 0");

                            t.HasCheckConstraint("ck_catalog_item_scale", "\"QuantityScale\" > 0");

                            t.HasCheckConstraint("ck_catalog_item_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.ConflictLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConflictId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CountedScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceiptLineId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SentScaled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConflictId");

                    b.HasIndex("ReceiptLineId")
                        .IsUnique();

                    b.ToTable("conflict_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_conflict_line_quantity", "\"SentScaled\" >= 0 AND \"CountedScaled\" >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.CorrectionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountDeltaMinor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CorrectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginalSaleLineId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityDeltaScaled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RestockScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrectionId", "OriginalSaleLineId")
                        .IsUnique();

                    b.ToTable("correction_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_correction_line_quantity", "\"QuantityDeltaScaled\" < 0 AND \"AmountDeltaMinor\" < 0 AND \"RestockScaled\" >= 0 AND \"QuantityScale\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.CustomOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CafeCustomerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CafeCustomerId");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status", "DueAtUtc");

                    b.ToTable("custom_orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_custom_order_money", "\"TotalMinor\" >= 0");

                            t.HasCheckConstraint("ck_custom_order_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.CustomOrderActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("CustomOrderId", "OccurredAtUtc");

                    b.ToTable("custom_order_activities", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.CustomOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomOrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("LineTotalMinor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuantityScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomOrderId", "ItemId")
                        .IsUnique();

                    b.ToTable("custom_order_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_custom_order_line_values", "\"QuantityScaled\" > 0 AND \"QuantityScale\" > 0 AND \"UnitPriceMinor\" >= 0 AND \"LineTotalMinor\" >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.CustomOrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CafeCustomerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("CafeCustomerId", "PaidAtUtc");

                    b.HasIndex("CustomOrderId", "PaidAtUtc");

                    b.ToTable("custom_order_payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_custom_order_payment_amount", "\"AmountMinor\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.DeviceConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceCredential")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TouchMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("device_configuration", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_configuration_singleton", "\"Id\" = 1");

                            t.HasCheckConstraint("ck_device_configuration_type1", "\"Profile\" IN ('BranchType1', 'BranchType2')");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("sync_inbox", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.IncomingReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CountedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceivingShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("incoming_receipts", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.IncomingReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ConfirmedScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CountedScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SentScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShipmentLineId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentLineId")
                        .IsUnique();

                    b.HasIndex("ReceiptId", "ItemId")
                        .IsUnique();

                    b.ToTable("incoming_receipt_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_receipt_line_quantity", "\"SentScaled\" > 0 AND \"CountedScaled\" >= 0 AND (\"ConfirmedScaled\" IS NULL OR \"ConfirmedScaled\" >= 0)");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.KitchenRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("BusinessDate", "RequestedAtUtc");

                    b.ToTable("kitchen_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_kitchen_request_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.KitchenRequestLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ApprovedScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestedScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SentScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestId", "ItemId")
                        .IsUnique();

                    b.ToTable("kitchen_request_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_kitchen_request_line_quantity", "\"RequestedScaled\" > 0 AND \"QuantityScale\" > 0 AND \"SentScaled\" >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.KitchenReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DispatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("ShiftId", "DispatchedAtUtc");

                    b.ToTable("kitchen_returns", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.KitchenReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SentScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId", "ItemId")
                        .IsUnique();

                    b.ToTable("kitchen_return_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_kitchen_return_line_quantity", "\"SentScaled\" > 0 AND \"QuantityScale\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependenciesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("DeviceSequence")
                        .IsUnique();

                    b.HasIndex("State", "NextAttemptAtUtc");

                    b.ToTable("sync_outbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_sequence", "\"DeviceSequence\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.QuantityConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.ToTable("quantity_conflicts", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.RefundPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CorrectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrectionId")
                        .IsUnique();

                    b.ToTable("refund_payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_refund_payment_amount", "\"AmountMinor\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.RemoteStockProjection", b =>
                {
                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuantityScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("SiteId", "ItemId");

                    b.ToTable("remote_stock_projections", null, t =>
                        {
                            t.HasCheckConstraint("ck_remote_stock_scale", "\"QuantityScale\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.ReportArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId", "ReportVersion")
                        .IsUnique();

                    b.ToTable("report_artifacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_report_artifact", "\"ReportVersion\" > 0 AND \"Format\" = 'xlsx' AND \"ByteLength\" >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fulfillment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SubtotalMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TipMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("ShiftId");

                    b.HasIndex("BusinessDate", "OccurredAtUtc");

                    b.ToTable("sales", null, t =>
                        {
                            t.HasCheckConstraint("ck_sale_money", "\"SubtotalMinor\" >= 0 AND \"DiscountMinor\" >= 0 AND \"TipMinor\" >= 0 AND \"TotalMinor\" >= 0");

                            t.HasCheckConstraint("ck_sale_total", "\"TotalMinor\" = \"SubtotalMinor\" - \"DiscountMinor\" + \"TipMinor\"");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.SaleCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginalSaleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostingShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RefundTotalMinor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("OriginalSaleId", "OccurredAtUtc");

                    b.ToTable("sale_corrections", null, t =>
                        {
                            t.HasCheckConstraint("ck_sale_correction_refund", "\"RefundTotalMinor\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AllocatedDiscountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuantityScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleId", "ItemId")
                        .IsUnique();

                    b.ToTable("sale_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_sale_line_money", "\"UnitPriceMinor\" >= 0 AND \"AllocatedDiscountMinor\" >= 0 AND \"TotalMinor\" >= 0");

                            t.HasCheckConstraint("ck_sale_line_quantity", "\"QuantityScaled\" > 0 AND \"QuantityScale\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.SalePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("sale_payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_sale_payment_amount", "\"AmountMinor\" >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.SequenceState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextCustomOrderSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextDeviceSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextReceiptSequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sequence_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_sequence_positive", "\"NextDeviceSequence\" > 0 AND \"NextReceiptSequence\" > 0 AND \"NextCustomOrderSequence\" > 0");

                            t.HasCheckConstraint("ck_sequence_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActualCashMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpectedCashMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningCashMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Open'");

                    b.HasIndex("BusinessDate", "Kind");

                    b.ToTable("shifts", null, t =>
                        {
                            t.HasCheckConstraint("ck_shift_cash", "\"OpeningCashMinor\" >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.ShiftItemSnapshot", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActualCloseScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AdjustmentScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CafeIssuedScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerRestockScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DiscrepancyScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpectedCloseScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IncomingScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KitchenReturnScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningQuantityScaled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SoldScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long>("WasteScaled")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShiftId", "ItemId");

                    b.ToTable("shift_item_snapshots", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DispatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyntheticDemo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Status", "DispatchedAtUtc");

                    b.ToTable("shipments", null, t =>
                        {
                            t.HasCheckConstraint("ck_shipment_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.ShipmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RequestLineId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SentScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestLineId");

                    b.HasIndex("ShipmentId", "ItemId")
                        .IsUnique();

                    b.ToTable("shipment_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_shipment_line_quantity", "\"SentScaled\" > 0 AND \"QuantityScale\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.SideEffectJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State", "NextAttemptAtUtc");

                    b.HasIndex("SourceId", "Kind", "DocumentVersion")
                        .IsUnique();

                    b.ToTable("side_effect_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_side_effect_job_version", "\"DocumentVersion\" > 0 AND \"Attempts\" >= 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.StockBalance", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityScaled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("stock_balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_balance_nonnegative", "\"QuantityScaled\" >= 0");

                            t.HasCheckConstraint("ck_stock_balance_revision", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.StockCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CountedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("ShiftId")
                        .IsUnique();

                    b.ToTable("stock_counts", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.StockCountLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ActualScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DifferenceScaled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpectedScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityScale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountId", "ItemId")
                        .IsUnique();

                    b.ToTable("stock_count_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_count_line_quantity", "\"ExpectedScaled\" >= 0 AND \"ActualScaled\" >= 0 AND \"QuantityScale\" > 0 AND \"DifferenceScaled\" = \"ActualScaled\" - \"ExpectedScaled\"");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.StockHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PhysicalCountScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReceiptLineId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReleasedScaled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptLineId")
                        .IsUnique();

                    b.HasIndex("Status", "ItemId");

                    b.ToTable("stock_holds", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_hold_quantity", "\"PhysicalCountScaled\" >= 0 AND \"ReleasedScaled\" >= 0 AND \"ReleasedScaled\" <= \"PhysicalCountScaled\"");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DeltaScaled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceLineId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "OccurredAtUtc");

                    b.HasIndex("SourceLineId", "Kind")
                        .IsUnique();

                    b.ToTable("stock_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_movement_nonzero", "\"DeltaScaled\" <> 0");
                        });
                });

            modelBuilder.Entity("SugarERP.Domain.SyncCursor", b =>
                {
                    b.Property<string>("FeedScope")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cursor")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotVersion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("FeedScope");

                    b.ToTable("sync_cursors", (string)null);
                });

            modelBuilder.Entity("SugarERP.Domain.BranchInventoryTransactionLine", b =>
                {
                    b.HasOne("SugarERP.Domain.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SugarERP.Domain.BranchInventoryTransaction", "Transaction")
                        .WithMany("Lines")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("SugarERP.Domain.BranchLocationBalance", b =>
                {
                    b.HasOne("SugarERP.Domain.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SugarERP.Domain.CafePrice", b =>
                {
                    b.HasOne("SugarERP.Domain.CafeCustomer", "Customer")
                        .WithMany("Prices")
                        .HasForeignKey("CafeCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SugarERP.Domain.CatalogItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SugarERP.Domain.ConflictLine", b =>
                {
                    b.HasOne("SugarERP.Domain.QuantityConflict", "Conflict")
                        .WithMany("Lines")
                        .HasForeignKey("ConflictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conflict");
                });

            modelBuilder.Entity("SugarERP.Domain.CorrectionLine", b =>
                {
                    b.HasOne("SugarERP.Domain.SaleCorrection", "Correction")
                        .WithMany("Lines")
                        .HasForeignKey("CorrectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Correction");
                });

            modelBuilder.Entity("SugarERP.Domain.CustomOrder", b =>
                {
                    b.HasOne("SugarERP.Domain.CafeCustomer", "CafeCustomer")
                        .WithMany("Orders")
                        .HasForeignKey("CafeCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CafeCustomer");
                });

            modelBuilder.Entity("SugarERP.Domain.CustomOrderActivity", b =>
                {
                    b.HasOne("SugarERP.Domain.CustomOrder", "Order")
                        .WithMany("Activities")
                        .HasForeignKey("CustomOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SugarERP.Domain.CustomOrderLine", b =>
                {
                    b.HasOne("SugarERP.Domain.CustomOrder", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("CustomOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SugarERP.Domain.CustomOrderPayment", b =>
                {
                    b.HasOne("SugarERP.Domain.CafeCustomer", null)
                        .WithMany()
                        .HasForeignKey("CafeCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SugarERP.Domain.CustomOrder", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("CustomOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SugarERP.Domain.IncomingReceipt", b =>
                {
                    b.HasOne("SugarERP.Domain.Shipment", "Shipment")
                        .WithOne("Receipt")
                        .HasForeignKey("SugarERP.Domain.IncomingReceipt", "ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("SugarERP.Domain.IncomingReceiptLine", b =>
                {
                    b.HasOne("SugarERP.Domain.IncomingReceipt", "Receipt")
                        .WithMany("Lines")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("SugarERP.Domain.KitchenRequestLine", b =>
                {
                    b.HasOne("SugarERP.Domain.KitchenRequest", "Request")
                        .WithMany("Lines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SugarERP.Domain.KitchenReturnLine", b =>
                {
                    b.HasOne("SugarERP.Domain.KitchenReturn", "Return")
                        .WithMany("Lines")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("SugarERP.Domain.RefundPayment", b =>
                {
                    b.HasOne("SugarERP.Domain.SaleCorrection", "Correction")
                        .WithOne("Payment")
                        .HasForeignKey("SugarERP.Domain.RefundPayment", "CorrectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Correction");
                });

            modelBuilder.Entity("SugarERP.Domain.Sale", b =>
                {
                    b.HasOne("SugarERP.Domain.Shift", "Shift")
                        .WithMany("Sales")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SugarERP.Domain.SaleLine", b =>
                {
                    b.HasOne("SugarERP.Domain.Sale", "Sale")
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SugarERP.Domain.SalePayment", b =>
                {
                    b.HasOne("SugarERP.Domain.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SugarERP.Domain.ShiftItemSnapshot", b =>
                {
                    b.HasOne("SugarERP.Domain.Shift", "Shift")
                        .WithMany("OpeningItems")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SugarERP.Domain.ShipmentLine", b =>
                {
                    b.HasOne("SugarERP.Domain.Shipment", "Shipment")
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("SugarERP.Domain.StockBalance", b =>
                {
                    b.HasOne("SugarERP.Domain.CatalogItem", "Item")
                        .WithOne("StockBalance")
                        .HasForeignKey("SugarERP.Domain.StockBalance", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SugarERP.Domain.StockCountLine", b =>
                {
                    b.HasOne("SugarERP.Domain.StockCount", "Count")
                        .WithMany("Lines")
                        .HasForeignKey("CountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Count");
                });

            modelBuilder.Entity("SugarERP.Domain.BranchInventoryTransaction", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SugarERP.Domain.CafeCustomer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("SugarERP.Domain.CatalogItem", b =>
                {
                    b.Navigation("StockBalance");
                });

            modelBuilder.Entity("SugarERP.Domain.CustomOrder", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SugarERP.Domain.IncomingReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SugarERP.Domain.KitchenRequest", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SugarERP.Domain.KitchenReturn", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SugarERP.Domain.QuantityConflict", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SugarERP.Domain.Sale", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SugarERP.Domain.SaleCorrection", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SugarERP.Domain.Shift", b =>
                {
                    b.Navigation("OpeningItems");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("SugarERP.Domain.Shipment", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("SugarERP.Domain.StockCount", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
