server {
    listen 80;
    listen [::]:80;
    server_name ascendyz.xyz;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        add_header Content-Type text/plain;
        return 503 'Sugar API is waiting for verified DNS and HTTPS.\n';
    }
}
