<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AvaloniaNameGeneratorIsEnabled>false</AvaloniaNameGeneratorIsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SugarERP.Application\SugarERP.Application.csproj" />
    <ProjectReference Include="..\SugarERP.Domain\SugarERP.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" ExcludeAssets="analyzers" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
  <Target Name="RemoveIncompatibleAvaloniaAnalyzers" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Analyzer Remove="@(Analyzer)" Condition="$([System.String]::Copy('%(Analyzer.FileName)').StartsWith('Avalonia.'))" />
    </ItemGroup>
  </Target>
</Project>
